net: OCRNet
num_classes: 3
backbone:
    initializer: hrnet_seg_w48
    pretrained: True
    backbone_ckpt: "" # If on modelarts, set the name of checkpoint saved in data_url
    in_channels: 3
fcn_head:
    in_channels: [48, 96, 192, 384]
    channels: 720
    kernel_size: 1
    num_convs: 1
    concat_input: False
    in_index: [0, 1, 2, 3]
    norm: "bn"
    act: "relu"
ocr_head:
    in_channels: [48, 96, 192, 384]
    channels: 512
    in_index: [0, 1, 2, 3]
    ocr_channels: 256
    norm: "bn"
    act: "relu"
loss_weight: [1.0, 0.4]
